<?php
// if($state == 'failed'){
// 	$response['status'] = 'F9';
// 	$response['reason'] = 'ping failed';
// 	$response['message'] = 'A failure response was initiated';
// }
// elseif($state == 'success'){
// 	$response['status'] = 'OK';
// 	$response['record'] = 1;
// 	$response['recordset'] = array('project' => $harvest->project['name'], 'version' => $harvest->project['version']);
// }

if($state == 'default'){

}