<?php
/**AO™ Library is a vanilla and evolving framework for developing websites, applications, and APIs using web technology.
 * Originator: Anthony O. Osawere - @iamodao - www.osawere.com  © 2020 | Apache License
 * ============================================================================================
 * oSQL ~ SQL Utility • DEPENDENCY»
 */
class oSQL {

	//METHOD • Describe method
	public static function FuncName(){return;}


} // EndOfClass - oSQL