-- CHANGE TABLE ENGINE
ALTER TABLE `table` ENGINE = INNODB;



-- USING CHINESE CHARACTER ON DATABASE
ALTER DATABASE `database` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

-- ALTER COLUM IN TABLE (CHINESE CHARACTER)
ALTER TABLE `table` CHANGE `location` `location` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;

-- CREATE TABLE WITH (CHINESE CHARACTER)
CREATE TABLE `table` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    `words` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE = InnoDB;




ALTER TABLE `firm`
CHANGE COLUMN `sendmail` `sendmail` CHAR(50) NULL DEFAULT 'no' AFTER `lang`;


ALTER TABLE `firm`
ADD COLUMN `sendmail` CHAR(50) NULL DEFAULT 'no' AFTER `lang`;