			<div class="container"><!-- STRART CONTAINER -->

			<div class="row">

			<div class="col-mg-4 col-md-4 col-sm-5 col-xs-12">

			<div class="footer_logo">

			<img src="/grafix/logo.png" alt="footer_logo">

			</div>

			<div class="site_info">

			<ul class="list_none">

			<li><i class="fa fa-map-marker"></i><p>20 Bond Street, Sydney NSW 2000 . Australia</p></li>

			<!-- <li><i class="fa fa-phone"></i><a href="tel:123456789">(1234) 12345-678 </a></li> -->

			<li><i class="fa fa-envelope"></i><a href="mailto:info@ricmogroup.com">info@ricmogroup.com</a>	</li>

			</ul>

			</div>

			</div>

			<div class="col-mg-8 col-md-8 col-sm-7 col-xs-12">

			<div class="newsletter_content">

			<h3 class="footer_title">Newsletter</h3>

			<p>By subscribing to our mailing list you will always be update with the latest news from us.</p>

			<div class="newsletter_form">

			<form>

			<input type="email" required="required" placeholder="Enter Your Email" class="form-control">

			<button type="submit">Subscribe</button>

			</form>

			</div>

			</div>

			</div>

			</div>

			</div><!-- END CONTAINER-->

			</div>