<?php
// echo $path;

// // $session = new oSession;
// // $session->start();
// // oSSL::Impose(true);
// // oFile::Inc(oRoute::Path('setting'));
// // $model = oRoute::model();
// // $pathz['organizr'] = oRoute::path('organizr');
// // $state = oRoute::state();
// // $action = oRoute::action();
// // $source = oRoute::path('source');

// #BEGIN API CODEBASE
// if(oRoute::api() != false){
// }
// #END API CODEBASE





// #BEGIN APP CODEBASE
// if(oRoute::app() != false){
// 	// require ($pathz['organizr'].'app'.DS.oRoute::model().'.inc');
// }
// #END APP CODEBASE





// #BEGIN SITE CODEBASE
// if(oRoute::site() != false){
// }
// #END SITE CODEBASE

// // if(oRoute::site() != false){
// 	// oFile::Inc(oRoute::path('themezr').'site.inc');
// 	// $page = oRoute::page();
// 	// echo oPrint::Neat(CONFIG);
// // }