	<div class="color-switch">
		<p>Color Switcher</p>
		<div class="color_box">
			<button value="theme" data-color="#ff880e" style="background:#ff880e;" class="active"></button>
			<button value="theme-red" data-color="#ff0000" style="background:#ff0000;"></button>
			<button value="theme-green" data-color="#1aca79" style="background:#1aca79;"></button>
			<button value="theme-pink" data-color="#F7378A" style="background:#F7378A;"></button>
			<button value="theme-purple" data-color="#8a2be2" style="background:#8a2be2;"></button>
			<button value="theme-lightblue" data-color="#05b5ff" style="background:#05b5ff;"></button>
		</div>
		<div class="icon"><i class="fa fa-cog" aria-hidden="true"></i></div>
	</div>