	<header class="navbar">
		<nav class="navbar navbar-default navbar-fixed white no-background bootsnav">
			<!-- Start Top Search -->
			<div class="top-search">
				<div class="container">
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-search"></i></span>
						<input type="text" class="form-control" placeholder="Search">
						<span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="attr-nav">
					<ul>
						<!-- <li class="search"><a href="#"><i class="fa fa-search"></i></a></li> -->
						<!-- <li class="user"><a href="#"><i class="fa fa-user"></i></a></li> -->
					</ul>
				</div>
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
						<i class="fa fa-bars"></i>
					</button>
					<a class="navbar-brand page-scroll" href="#home">
						<img src="/grafix/logo.png" class="logo logo-display" alt="logo">
						<img src="/grafix/logo-alt.png" class="logo logo-scrolled" alt="logo">
					</a>
				</div>
				<div class="collapse navbar-collapse" id="navbar-menu">
					<ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
						<li><a class="page-scroll" href="#home" onclick="setTitle('Home');">Home</a></li>
						<li><a class="page-scroll" href="#about" onclick="setTitle('About Us');">About Us</a></li>
						<li><a class="page-scroll" href="#whychoose" onclick="setTitle('Why Choose Us');">Why Ricmo</a></li>
						<li><a class="page-scroll" href="#team" onclick="setTitle('Our CEO');">CEO</a></li>
						<li><a class="page-scroll" href="#footer" onclick="setTitle('Contact Us');">Contact Us</a></li>
						<li><a class="page-scroll" href="/app/register">Register</a></li>
						<li><a class="page-scroll" href="/app/login">Login</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>