<section>
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading text-center">
					<h2>OUR RECORDS</h2>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="btcwdgt-chart"></div>
			</div>
		</div>

	</div><!-- END CONTAINER-->
</section>