	<script src="/js/jquery.js"></script>
	<script src="/js/bootstrap.js"></script>
	<script src="/js/bootsnav.js"></script>
	<script src="/plugin/owl/js/carousel.js"></script>
	<script src="/js/magnific-popup.js"></script>
	<script src="/js/waypoints.js"></script>
	<script src="/js/jquery.counterup.js"></script>
	<script src="/js/scripts.js"></script>
	<script src="//code.tidio.co/g95iyewhqgsrfgv6gksxjlfet7hleyir.js" async></script>
	<script type="text/javascript">
		function setTitle(title){
			var title_now = title+' - Ricmo Investment Group';
			if(document.title != title_now){
				document.title = title_now;
			}
			return false;
		}
	</script>