	<section class="counter_wrap overlay background_bg" style="background-image:url(assets/images/counter_bg.jpg);">
		<div class="container"><!-- STRART CONTAINER -->
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="counter_box">
						<i class="fa fa-pie-chart"></i>
						<span class="counter">500</span>
						<h6>Recurring Investment</h6>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="counter_box">
						<i class="fa fa-life-ring"></i>
						<span class="counter">40</span>
						<h6>Support Countries</h6>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="counter_box">
						<i class="fa fa-shield"></i>
						<span class="counter">1258</span>
						<h6>New Investment</h6>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="counter_box">
						<i class="fa fa-users"></i>
						<span class="counter">2500</span>
						<h6>Payouts</h6>
					</div>
				</div>

			</div>
		</div><!-- END CONTAINER-->
	</section>