<section>
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading text-center">
					<h2>Our Partner</h2>
					<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim <br>id est laborum. Perspiciatis unde omnis iste natus error sit.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="partner_slider owl-carousel owl-theme">
					<div class="item">
						<div class="partner_logo">
							<a href="#"><img src="assets/images/partner_logo1.png" alt="partner_logo1"></a>
						</div>
					</div>
					<div class="item">
						<div class="partner_logo">
							<a href="#"><img src="assets/images/partner_logo2.png" alt="partner_logo2"></a>
						</div>
					</div>
					<div class="item">
						<div class="partner_logo">
							<a href="#"><img src="assets/images/partner_logo3.png" alt="partner_logo3"></a>
						</div>
					</div>
					<div class="item">
						<div class="partner_logo">
							<a href="#"><img src="assets/images/partner_logo4.png" alt="partner_logo4"></a>
						</div>
					</div>
					<div class="item">
						<div class="partner_logo">
							<a href="#"><img src="assets/images/partner_logo5.png" alt="partner_logo5"></a>
						</div>
					</div>
					<div class="item">
						<div class="partner_logo">
							<a href="#"><img src="assets/images/partner_logo6.png" alt="partner_logo6"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div><!-- END CONTAINER-->
</section>