-- UPDATE PUID, EUID & SUID
USE `aodb`;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `_sample`
	CHANGE COLUMN `author` `author` VARCHAR(80) NULL DEFAULT NULL AFTER `stamp`,
	ADD COLUMN `puid` CHAR(20) NULL DEFAULT NULL AFTER `author`,
	CHANGE COLUMN `euid` `euid` CHAR(40) NULL DEFAULT NULL AFTER `puid`,
	CHANGE COLUMN `suid` `suid` CHAR(70) NULL DEFAULT NULL AFTER `euid`,
	ADD INDEX `puid` (`puid`);
SET FOREIGN_KEY_CHECKS = 1;



-- TRUNCATE TABLE
USE `aodb`;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE `_sample`;
SET FOREIGN_KEY_CHECKS = 1;


-- RESET & RENUMBER PRIMARY KEY
USE `aodb`;
SET FOREIGN_KEY_CHECKS = 0;
SET @NewID = 0;
UPDATE `_sample` SET `auid`=(@NewID := @NewID +1) ORDER BY `auid`;
SELECT MAX(`auid`) AS `IDMax` FROM `_sample`;
ALTER TABLE `_sample` AUTO_INCREMENT = 1;
SET FOREIGN_KEY_CHECKS = 1;