	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Ricmo is a modern and elegant landing page, created for Ricmo Agencies and digital crypto currency investment website.">
	<title> Ricmo - Ricmo Investment Group</title>
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.png?">
	<link type="text/css" rel="stylesheet" href="/css/animate.css" >
	<link type="text/css" rel="stylesheet" href="/css/bootstrap.css">
	<link type="text/css" href="/css/bootsnav.css" rel="stylesheet">
	<link type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="/font/font-awesome.css">
	<link type="text/css" rel="stylesheet" href="/plugin/owl/css/carousel.css">
	<link type="text/css" rel="stylesheet" href="/plugin/owl/css/theme.css">
	<link type="text/css" rel="stylesheet" href="/css/magnific-popup.css">
	<link type="text/css" rel="stylesheet" href="/css/style.css" media="all">
	<link type="text/css" rel="stylesheet" href="/css/responsive.css">
	<!-- <link id="layoutstyle" type="text/css" rel="stylesheet" href="assets/color/theme.css"> -->