<div class="bottom_footer">
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-mg-6 col-md-6 col-sm-8 col-xs-12">
				<div class="copyright_text">
					<p>&copy; Copyright 2020  Ricmo.</p>
				</div>
			</div>
			<div class="col-mg-6 col-md-6 col-sm-4 col-xs-12">
				<div class="social_footer list_none text-right">
					<ul>
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
						<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
					</ul>
				</div>
			</Div>
		</div>
	</div><!-- END CONTAINER-->
</div>