<section class="get_now_wrap">
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading text-center">
					<h2>Get Started Today</h2>
					<!-- <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim <br>id est laborum. Perspiciatis unde omnis iste natus error sit.</p> -->
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 no-padding">
				<div class="get_start_box bg_color1 text-center">
					<i class="fa fa-download"></i>
					<h3>Register on Ricmo</h3>
					<p>Please <a href="/app/register" style="color: white; text-decoration: underline;">register</a> or <a href="/app/login" style="color: white; text-decoration: underline;">login</a></p>
				</div>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 no-padding">
				<div class="get_start_box bg_color2 text-center">
					<i class="fa fa-folder-open"></i>
					<h3>Fund your Investment</h3>
					<p>Fund your account for investment easily</p>
				</div>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 no-padding">
				<div class="get_start_box bg_color1 text-center">
					<i class="fa fa-refresh"></i>
					<h3>Receive your Dividend</h3>
					<p>You can receive your dividend when due</p>
				</div>
			</div>
		</div>
	</div><!-- END CONTAINER-->
</section>