<section class="overlay background_bg" style="background-image:url(assets/images/video_bg.jpg);">
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
				<div class="video_box">
					<div class="heading text-center white">
						<h2>Video Review</h2>
						<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim </p>
					</div>
					<a class="video" href="https://www.youtube.com/watch?v=GmOzih6I1zs"><i class="fa fa-play"></i></a>
				</div>
			</div>
		</div>
	</div><!-- END CONTAINER-->
</section>