<h4 class="heading">Whosco Privacy Statement</h4>
    <article class="container"> <h4 class="hide">Privacy Policy Statement of Whosco Ventures Limited</h4>
      <p>Whosco take your privacy seriously. In general, you can visit Whosco Scientific on the Web without identifying yourself or revealing any personal information. Once you choose to provide us personally identifiable information (any information by which you can be identified or reached), you can be assured that it will only be used to support your relationship with us. We provide this online Privacy Statement to make you aware of our privacy policy and practices and of the choices you can make about the way your information is collected and used.</p>
      <p class="spaced">Within Whosco Scientific website, you can order products or services, make requests and register to receive materials. The types of personal information collected at these pages may include your name, your company name, address, telephone number, e-mail address, contact and billing information (including shipping address and end user, transaction details and many more; depending on what you are actually doing on our website.</p>
      <p>When information is collected from you, we generally let you know at the time of collection how we will use it - typically only to respond to your inquiry or to process your request or to better understand your needs and provide you with better service. Specifically, we use your information to help you complete a transaction, to communicate back to you, to update you on services and benefits and to personalize our website for you.</p>
<p class="spaced">However, we may need to share your information with our subsidiaries or with other companies that we have hired to provide the services that you requested if services are or will be provided by third party organization. These companies - our vendors - are contractually bound to use personal information we share with them only to perform the services we have hired them to provide. We do not share, sell or lease personal information about you to any third parties for their marketing use. From time to time, we may also use your information to contact you for market research or to provide you with marketing information we think would be of particular interest. At a minimum, we will always give you the option of receiving such direct marketing or market research contact.</p>
  <p>Whosco Scientific is committed to ensuring the security of your information. To prevent unauthorized access or disclosure, maintain data accuracy and ensure the appropriate use of information, we have put in place appropriate physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p>
  <p class="spaced">Whosco Scientific website may contain links to other sites, such as Whosco distributors and sales affiliates. While we try to link only to sites that share our high standards and respect for privacy, we are not responsible for the content, security or privacy practices employed by other sites. You are solely responsible for evaluating the privacy practices employed by those sites.</p>
    <p>Please check this privacy policy periodically to inform yourself of any changes. We reserve the right to modify or supplement this privacy policy from time to time without notice to you.</p>
    <p class="spaced">If you have comments or questions about our privacy policy, please visit the "contact us" page to contact us and we shall respond to you shortly.</p>
    </article>
