<h4 class="heading">Whosco Scientific Terms and Conditions </h4>
    <article class="container"> <h4 class="hide">Terms and Conditions of Whosco Ventures Limited</h4>
      <p><strong>ATTENTION: PLEASE READ THESE TERMS CAREFULLY BEFORE ACCESSING OR USING THIS WEBSITE. USING THIS WEBSITE INDICATES THAT YOU ACCEPT THESE TERMS. IF YOU DO NOT ACCEPT THESE TERMS OF OUR SERVICES ("TERMS"), PLEASE DO NOT USE THIS WEBSITE</strong></p>
      <p class="spaced"><strong>Use of Website.</strong> Whosco Scientific authorizes you to view, print and download material like price list at this Website ("www.whosco.com") only for your use in case you want to do business with us, provided that you retain all copyright and other proprietary notices contained in the original materials on any copies of the materials downloaded or printed from the Site. You may not modify the materials at this Site in any way or reproduce or publicly display, perform or distribute or otherwise use them for any public or commercial purpose. For purposes of these Terms of Services, the use of Whosco materials on any other website or networked computer environment for any purpose is prohibited. The materials at this Site are copyrighted and any unauthorized use of any materials at this Site may violate copyright, trademark and other laws. You agree that you will not disclose, republish, reproduce or distribute any of the information displayed on or comprising this Site (the "Content") or make any use of the Content that will allow a third party to have access to the Content. If you breach any of these Terms, your authorization to use this Site automatically terminates and you must immediately destroy any downloaded or printed materials.</p>
      <p><strong>Modification of Terms</strong>. Whosco may modify these Terms at any time, and such modifications shall be effective immediately upon posting of the modified Terms. You agree to review these Terms periodically to be aware of such modifications and your continued access or use of the Site shall be deemed your conclusive acceptance of the modified Terms.</p>
<p class="spaced"><strong>Modification of Products and Prices.</strong> Whosco may modify the prices of products or change the kind of products displayed on www.whosco.com website. And such modification shall be effective immediately upon posting it, and these modification may or will be done without informing you except you have signup for our newsletter.</p>
 <p><strong>Use of Software.</strong> If you download any software from this Site ("Software"), use of the Software is subject to the license terms in the Software License Agreement that accompanies or is provided with the Software. You may not download or install the Software until you have read and accepted the terms of the Software License Agreement.</p>
  <p class="spaced"><strong>Proprietary Materials.</strong> Trademarks, logos, images, illustrations, video clips, file text and graphics used or displayed at this Site are copyrights, trademarks, and or intellectual property owned, controlled, registered or licensed by Whosco Scientific or its affiliates or third-party owners.</p>
 <p><strong>User Submissions.</strong> Any information or other communication you transmit or post to this Site ("Communication") is, and will be treated as confidential and handled with high security guards; and  the information posted on our news letter subscription form shall be use for it purpose [mainly transmission of information].</p>
 <p class="spaced"><strong>Links To Other Websites.</strong>. Links to third-party websites on this Site are provided solely as a convenience to you. If you use these links, you will leave this Site. Whosco Ventures  Limited has not reviewed all of these third-party sites and does not control and is not responsible for any of these sites or their content. Thus, Whosco does not endorse or make any representations about them, or any information, software or other products or materials found there, or any results that may be obtained from using them. If you decide to access any of the third-party sites linked to this Site, you do this entirely at your own risk and you also understand that Whosco cannot and does not guarantee or warrant the files and content available for downloading through those Site are or will be free of infection or viruses, worms, Trojan horses or other code that manifest contaminating or destructive properties. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for accuracy of data input and output, and for maintaining a means external to the Site for the reconstruction of any lost data.</p>
 <p><strong>Indemnification.</strong> You agree to indemnify, defend and hold harmless Whosco Ventures Limited, its officers, directors, employees, agents, affiliates, licensors, suppliers and any third-party information providers to the Site from and against all losses, expenses, damages and costs, including reasonable attorneys' fees, resulting from any violation of these Terms by you.</p>
</article>
