<?php
//========== APPLICATION SETTINGS ==========//
$o_app = array(
	'firm'    => 'BRUX Application Framework',
	'abbr'    => 'BRUX Framework',
	'brand'   => 'BRUX™',
	'acronym' => 'BRUX',
	'slogan'  => 'code your way',
	// 'url'     => 'https://www.brux.io',
	// 'path'    => '/brux/',
	// 'domain'  => 'brux.io',
	// 'email'   => 'code@brux.io',
	'phone'   => '+234 (902) 663 6728',
	'address'   => 'Sapele road, Benin city, Edo state, Nigeria',
	'useDB' => 'yeah',
	'imposeSSL' => 'yeah',
	'rewriteURL' => 'yeah',
	'mode' => 'live',
	'environ' => 'brux'
	);
?>