	<section id="home" class="banner_section no-padding overlay background_bg" style="background-image:url(assets/images/banner_1.jpg);">
		<canvas id="circle-canvas"></canvas>
		<div class="banner_content_wrap home_slider owl-carousel">
			<div class="item active">
				<div class="container"><!-- STRART CONTAINER -->
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-left">
							<div class="banner_content">
								<h2>Ricmo is the future!</h2>
								<p>Ricmo is the way to the future, you are ready.</p>
								<div class="slider_btn">
									<a href="#about" class="btn btn-primary page-scroll">Read More</a>
									<a href="#footer" class="btn btn-default page-scroll">Contact Us</a>
								</div>
							</div>
						</div>
					</div>
				</div><!-- END CONTAINER-->
			</div>
			<div class="item">
				<div class="container"><!-- STRART CONTAINER -->
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
							<div class="banner_content">
								<h2>Want to start trading?</h2>
								<p>The registration process is quick and involves three easy to follow steps.</p>
								<div class="slider_btn">
									<a href="#about" class="btn btn-primary page-scroll">Read More</a>
									<a href="#footer" class="btn btn-default page-scroll">Contact Us</a>
								</div>
							</div>
						</div>
					</div>
				</div><!-- END CONTAINER-->
			</div>
			<div class="item">
				<div class="container"><!-- STRART CONTAINER -->
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">
							<div class="banner_content">
								<h2>Lending & Investment</h2>
								<p>Ricmo Decentralized Consulting Platform is great for ICO Developers, Advisors, Crypto-Experts and Investors.</p>
								<div class="slider_btn">
									<a href="#about" class="btn btn-primary page-scroll">Read More</a>
									<a href="#footer" class="btn btn-default page-scroll">Contact Us</a>
								</div>
							</div>
						</div>
					</div>
				</div><!-- END CONTAINER-->
			</div>
		</div>
	</section>