	<section id="home" class="banner_section no-padding overlay background_bg" style="background-image:url(assets/images/banner_1.jpg);">
	<canvas id="circle-canvas"></canvas>
	<div class="banner_content_wrap home_slider owl-carousel">
	<div class="item active">
	<div class="container"><!-- STRART CONTAINER -->
	<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-left">
	<div class="banner_content">
	<h2>BitCurrency is the way to <br>the future, you are ready!</h2>
	<p>ICO Crypto Template, an ICO Landing page template that will<br> best for ICO Startup Agency.</p>
	<div class="slider_btn">
	<a href="#about" class="btn btn-primary page-scroll">Read More</a>
	<a href="#footer" class="btn btn-default page-scroll">Contact Us</a>
	</div>
	</div>
	</div>
	</div>
	</div><!-- END CONTAINER-->
	</div>
	<div class="item">
	<div class="container"><!-- STRART CONTAINER -->
	<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
	<div class="banner_content">
	<h2>ICO Landing page for your <br> cryptocurrency project</h2>
	<p>We are proud to introduce ICO Crypto Template, an ICO Landing page template that will<br> best for ICO Startup Agency. Know our advantage.</p>
	<div class="slider_btn">
	<a href="#about" class="btn btn-primary page-scroll">Read More</a>
	<a href="#footer" class="btn btn-default page-scroll">Contact Us</a>
	</div>
	</div>
	</div>
	</div>
	</div><!-- END CONTAINER-->
	</div>
	<div class="item">
	<div class="container"><!-- STRART CONTAINER -->
	<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">
	<div class="banner_content">
	<h2>BitCurrency <br> Lending & Investment Platform</h2>
	<p>Decentralized Consulting Platform for ICO Developers, Advisors, Crypto-Experts and Investors.</p>
	<div class="slider_btn">
	<a href="#about" class="btn btn-primary page-scroll">Read More</a>
	<a href="#footer" class="btn btn-default page-scroll">Contact Us</a>
	</div>
	</div>
	</div>
	</div>
	</div><!-- END CONTAINER-->
	</div>
	</div>
	</section>