	<header class="navbar">
	<nav class="navbar navbar-default navbar-fixed white no-background bootsnav">
	<!-- Start Top Search -->
	<div class="top-search">
	<div class="container"><!-- STRART CONTAINER -->
	<div class="input-group">
	<span class="input-group-addon"><i class="fa fa-search"></i></span>
	<input type="text" class="form-control" placeholder="Search">
	<span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
	</div>
	</div><!-- END CONTAINER-->
	</div>
	<!-- End Top Search -->
	<div class="container"><!-- STRART CONTAINER -->
	<!-- Start Atribute Navigation -->
	<div class="attr-nav">
	<ul>
	<li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
	<li class="user"><a href="#"><i class="fa fa-user"></i></a></li>
	</ul>
	</div>
	<!-- End Atribute Navigation -->

	<!-- Start Header Navigation -->
	<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
	<i class="fa fa-bars"></i>
	</button>
	<a class="navbar-brand page-scroll" href="#home">
	<img src="assets/images/logo.png" class="logo logo-display" alt="logo">
	<img src="assets/images/logo_black.png" class="logo logo-scrolled" alt="logo">
	</a>
	</div>
	<!-- End Header Navigation -->

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="navbar-menu">
	<ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
	<li><a class="page-scroll" href="#home">Home</a></li>
	<li><a class="page-scroll" href="#about">About Us</a></li>
	<li><a class="page-scroll" href="#whychoose">Why Choose</a></li>
	<li><a class="page-scroll" href="#team">Team</a></li>
	<li><a class="page-scroll" href="#blog">Blog</a></li>
	<li><a class="page-scroll" href="#footer">Contact Us</a></li>
	</ul>
	</div><!-- /.navbar-collapse -->
	</div><!-- END CONTAINER-->
	</nav>
	</header>