<?php
// echo '<h4 style="margin:0px;">DEBUG!</h4>';
// oDUMP($_REQUEST);
// oDUMP(oRouter::go());
// $demo = array(
// 	'Name' => 'Anthony Osawere',
// 	'Email' => 'ao@woca.ng',
// 	'Gender' => 'M',
// );
// echo json_encode($demo);
// oDUMP($_REQUEST);

// $sandbox = oRouter::info();
// oDUMP($sandbox);

// $dba = array(
// 	'host' => "localhost",
// 	'user' => "woca",
// 	'password' => "woca",
// 	'name' => "woca_bar",
// );

// require 'orax/php/dump.inc';
// require 'orax/php/exit.inc';
// require 'orax/php/file.inc';
// oFile::Inc('orax/php/json.inc');
// oFile::Inc('orax/php/database.inc');

// $database = new oDatabase($dba, 'pdo');



// $aHavest = aHavestConfig();
// $config_db = $aHavest['config']['database'];


// $database = new oDatabase($config_db);
// $dbo = $database->connect();

// $stmt = $dbo->prepare("CALL UsersAll()");
// $exec = $stmt->execute();
// $result = $stmt->fetchAll(PDO::FETCH_ASSOC);
// if($exec != false && !empty($result)){
// 	oJson::run($result, 'oPRINT');
// }
// $debug = '';
// echo oDump::Neat($database);
?>