	<!-- Meta -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Ricmo is a modern and elegant landing page, created for Ricmo Agencies and digital crypto currency investment website.">
	<!-- SITE TITLE -->
	<title> Ricmo - Ricmo Investment Group</title>
	<!-- Favicon Icon -->
	<link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png">
	<!-- Animation CSS -->
	<link type="text/css" rel="stylesheet" href="assets/css/animate.css" >
	<!-- Latest Bootstrap min CSS -->
	<link type="text/css" rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
	<!-- Navigation CSS -->
	<link type="text/css" href="assets/css/bootsnav.css" rel="stylesheet">
	<!-- Google Font -->
	<link type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<!-- Font Awesome CSS -->
	<link type="text/css" rel="stylesheet" href="assets/fonts/font-awesome.min.css">
	<!--- owl carousel CSS-->
	<link type="text/css" rel="stylesheet" href="assets/owlcarousel/css/owl.carousel.min.css">
	<link type="text/css" rel="stylesheet" href="assets/owlcarousel/css/owl.theme.css">
	<!-- Magnific Popup CSS -->
	<link type="text/css" rel="stylesheet" href="assets/css/magnific-popup.css">
	<!-- Style CSS -->
	<link type="text/css" rel="stylesheet" href="assets/css/style.css" media="all">
	<link type="text/css" rel="stylesheet" href="assets/css/responsive.css">
	<!-- Color CSS -->
	<!-- <link id="layoutstyle" type="text/css" rel="stylesheet" href="assets/color/theme.css"> -->