	<!-- Latest jQuery -->

	<script src="assets/js/jquery-1.12.4.min.js"></script>

	<!-- Latest compiled and minified Bootstrap -->

	<script src="assets/bootstrap/js/bootstrap.min.js"></script>

	<!-- Bootsnavs -->

	<script src="assets/js/bootsnav.js"></script>

	<!-- owl-carousel min js  -->

	<script src="assets/owlcarousel/js/owl.carousel.min.js"></script>

	<!-- magnific-popup min js  -->

	<script src="assets/js/magnific-popup.min.js"></script>

	<!-- waypoints min js  -->

	<script src="assets/js/waypoints.min.js"></script>

	<!-- counterup min js  -->

	<script src="assets/js/jquery.counterup.min.js"></script>

	<!-- scripts js -->

	<script src="assets/js/scripts.js"></script>


	<script src="//code.tidio.co/g95iyewhqgsrfgv6gksxjlfet7hleyir.js" async></script>