<?php
//========== SLIDE BANNER INFORMATION ==========//
$o_banner['landing'] = array(
	1	=> array(
		'name' => 'chair',
		'caption' => 'you will find rows of chairs on a stadium',
		'alt' => 'stadium chairs'),
	2 => array(
		'name' => 'swing',
		'caption' => 'children enjoy the out doors on a swing',
		'alt' => 'outdoor swing'),
	3 => array(
		'name' => 'tractor',
		'caption' => "using a tractor on a farm is mechanised farming",
	'alt' => 'tractor for farming')
	);
?>