<section class="gray_bg" id="blog">
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading text-center">
					<h2>Latest News</h2>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="blog_content owl-carousel owl-theme">
					<div class="item">
						<div class="blog">
							<figure>
								<a href="#"><img src="/grafix/blog_img1.jpg" alt="blog1"></a>
								<div class="blog_date"><span class="date"><i class="fa fa-calendar-o"></i>January 28,2018</span></div>
							</figure>
							<div class="content_blog">
								<h4><a href="#">But I must explain to you how all this mistaken idea</a></h4>
								<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
								<a href="#">Read more</a>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="blog">
							<figure>
								<a href="#"><img src="/grafix/blog_img2.jpg" alt="blog2"></a>
								<div class="blog_date"><span class="date"><i class="fa fa-calendar-o"></i>January 28,2018</span></div>
							</figure>
							<div class="content_blog">
								<h4><a href="#">But I must explain to you how all this mistaken idea</a></h4>
								<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
								<a href="#">Read more</a>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="blog">
							<figure>
								<a href="#"><img src="/grafix/blog_img3.jpg" alt="blog3"></a>
								<div class="blog_date"><span class="date"><i class="fa fa-calendar-o"></i>January 28,2018</span></div>
							</figure>
							<div class="content_blog">
								<h4><a href="#">But I must explain to you how all this mistaken idea</a></h4>
								<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
								<a href="#">Read more</a>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="blog">
							<figure>
								<a href="#"><img src="/grafix/blog_img4.jpg" alt="blog4"></a>
								<div class="blog_date"><span class="date"><i class="fa fa-calendar-o"></i>January 28,2018</span></div>
							</figure>
							<div class="content_blog">
								<h4><a href="#">But I must explain to you how all this mistaken idea</a></h4>
								<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
								<a href="#">Read more</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div><!-- END CONTAINER-->
</section>