	<section id="team">

		<div class="container"><!-- STRART CONTAINER -->

			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

					<div class="heading text-center">

						<h2>Our CEO</h2>

					</div>

				</div>

			</div>

			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

					<!-- <div class="team_slider owl-carousel owl-theme"> -->

						<div class="item">

							<div class="team_box text-center">

								<div class="team_img">

									<a href="#"><img src="assets/images/ceo.jpg" alt="ceo" style="max-height: 300px;"></a>

									<div class="team_social_wrap">

										<ul class="team_social">

											<li><a href="#"><i class="fa fa-facebook"></i></a></li>

											<li><a href="#"><i class="fa fa-twitter"></i></a></li>

											<li><a href="#"><i class="fa fa-linkedin"></i></a></li>

										</ul>

									</div>

								</div>

								<div class="team_content">

									<h3><a href="#">Carey Dean Joseph</a></h3>

									<p>(Co-Founder & CEO)</p>

								</div>

							</div>

						</div>

						<!-- <div class="item">

							<div class="team_box text-center">

								<div class="team_img">

									<a href="#"><img src="assets/images/team2.jpg" alt="team2"></a>

									<div class="team_social_wrap">

										<ul class="team_social">

											<li><a href="#"><i class="fa fa-facebook"></i></a></li>

											<li><a href="#"><i class="fa fa-twitter"></i></a></li>

											<li><a href="#"><i class="fa fa-linkedin"></i></a></li>

										</ul>

									</div>

								</div>

								<div class="team_content">

									<h3><a href="#">Maria Willium</a></h3>

									<p>(Co-Founder & CEO)</p>

								</div>

							</div>

						</div> -->

						<!-- <div class="item">

							<div class="team_box text-center">

								<div class="team_img">

									<a href="#"><img src="assets/images/team3.jpg" alt="team3"></a>

									<div class="team_social_wrap">

										<ul class="team_social">

											<li><a href="#"><i class="fa fa-facebook"></i></a></li>

											<li><a href="#"><i class="fa fa-twitter"></i></a></li>

											<li><a href="#"><i class="fa fa-linkedin"></i></a></li>

										</ul>

									</div>

								</div>

								<div class="team_content">

									<h3><a href="#">Maria Willium</a></h3>

									<p>(Co-Founder & CEO)</p>

								</div>

							</div>

						</div> -->

						<!-- <div class="item">

							<div class="team_box text-center">

								<div class="team_img">

									<a href="#"><img src="assets/images/team4.jpg" alt="team4"></a>

									<div class="team_social_wrap">

										<ul class="team_social">

											<li><a href="#"><i class="fa fa-facebook"></i></a></li>

											<li><a href="#"><i class="fa fa-twitter"></i></a></li>

											<li><a href="#"><i class="fa fa-linkedin"></i></a></li>

										</ul>

									</div>

								</div>

								<div class="team_content">

									<h3><a href="#">Maria Willium</a></h3>

									<p>(Co-Founder & CEO)</p>

								</div>

							</div>

						</div> -->



						<!-- </div> -->

					</div>

				</div>

			</div><!-- END CONTAINER-->

		</section>