<?php
//========== APPLICATION SETTINGS ==========//
$o_app = array(
	'firm'    => 'BRUX Application Framework',
	'abbr'    => 'BRUX Framework',
	'brand'   => 'BRUX™',
	'acronym' => 'BRUX',
	'slogan'  => 'code your way',
	'url'     => 'https://www.framework.net',
	// 'path'    => '/BRUX/',
	'domain'  => 'framework.net',
	'email'   => 'brux@framework.net',
	'phone'   => '+234 (902) 663 6728',
	'address'   => 'sapele road, benin city, edo state, nigeria',
	'imposeSSL' => 'yeah',
	'rewriteURL' => 'yeah',
	'mode' => 'live',
	'environ' => 'brux'
	);
?>