	<section class="about" id="about">
		<div class="container"><!-- STRART CONTAINER -->
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<div class="heading">
						<h2>About Ricmo</h2>
					</div>
					<p>Ricmo Investment Stock is a leading online trading service broker offering the possibility to trade in underlying assets as example BTC and currencies.<br><br>
						Our professional team of experts in cryptocurrency, web-commerce, financial trading and blockchain technology work together in making our services cost-effective for retail users.
						Ricmo Investment Stock brand is operated by Bayline Trading Limited which regulated by the Australian International Financial Services Commission (AFSC) under License No. AFSC/60/322/TS16.
					</p>
					<p>
					Ricmo Investment Stock has gained a reputation for success, leading to a stable base of worldwide users who make thousands of trades every month and profits every single day.</p>
					<!-- <a href="#" class="btn btn-default">Read More</a> -->
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<div class="single_img">
						<img src="/grafix/about.jpg" alt="about_img">
					</div>
				</div>
			</div>
		</div><!-- END CONTAINER-->
	</section>