<section id="footer" class="overlay background_bg" style="background-image:url('/grafix/contact.jpg');">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading text-center white">
					<h2>Contact us</h2>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
				<div class="contact_form">
					<form method="post" name="enq" class="form">
						<div class="row">
							<div class="form-group col-md-6">
								<input type="text" required="required" placeholder="Name" id="first-name" class="form-control" name="name">
							</div>
							<div class="form-group col-md-6">
								<input type="email" required="required" placeholder="Email" id="email" class="form-control" name="email">
							</div>
							<div class="form-group col-md-12">
								<input type="text" required="required" placeholder="Subject" id="subject" class="form-control" name="subject">
							</div>
							<div class="form-group col-md-12">
								<textarea required="required" placeholder="Your Message" id="description" class="form-control" name="message" rows="6"></textarea>
							</div>
							<div class="col-md-12">
								<div class="actions">
									<input type="submit" title="Submit Your Message!" class="btn btn-default" id="submitButton" name="submit" value="Send message">
								</div>
							</div>
							<div class="col-md-12">
								<div id="alert-msg" class="alert-msg"></div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
