<section class="gray_bg whychoose" id="whychoose">
	<div class="container"><!-- STRART CONTAINER -->
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading text-center">
					<h2>Why Choose Bitcoin</h2>
					<!-- <p>dddddddddd</p> -->
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="service_box text-center">
					<div class="service_icon">
						<img src="/grafix/icon1.png" alt="icon1">
					</div>
					<div class="service_text">
						<h4>Multiple Assets</h4>
						<p>A vast supply of financial assets. Very competitive fees. Training programs for new traders. Choose your own Leverage.</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="service_box text-center">
					<div class="service_icon">
						<img src="/grafix/icon2.png" alt="icon2">
					</div>
					<div class="service_text">
						<h4>Experts Support</h4>
						<p>Our customer support agents are always on ground to provide excellent care to your basic and technical inquiries</p>
					</div>
				</div>
			</div>
<!-- 	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
<div class="service_box text-center">
<div class="service_icon">
<img src="/grafix/icon3.png" alt="icon3">
</div>
<div class="service_text">
<h4>Mobile Apps</h4>
<p>You can access our platforms from any mobile device as it is built to be responsive.</p>
</div>
</div>
</div> -->
<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
	<div class="service_box text-center">
		<div class="service_icon">
			<img src="/grafix/icon4.png" alt="icon4">
		</div>
		<div class="service_text">
			<h4>Quick Withdrawal</h4>
			<p>Quick withdrawal process with an advanced information security system that protects your data.</p>
		</div>
	</div>
</div>
<!-- <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
<div class="service_box text-center">
<div class="service_icon">
<img src="/grafix/icon5.png" alt="icon5">
</div>
<div class="service_text">
<h4>Secure Wallet</h4>
<p>Keeping secure system for trading is especially important us; thus depositing and withdrawing your funds is made with the highest security measures.</p>
</div>
</div>
</div> -->
<!-- <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
<div class="service_box text-center">
<div class="service_icon">
<img src="/grafix/icon6.png" alt="icon6">
</div>
<div class="service_text">
<h4>Variety Buys</h4>
<p>User-friendly platforms tailored to both new and experienced traders.</p>
</div>
</div>
</div> -->
</div>
</div><!-- END CONTAINER-->
</section>