	<section class="price_rate wave_bg">
		<div class="container"><!-- STRART CONTAINER -->
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="rate_list text-center">
						<div class="rate_content">
							<h3>XRP</h3>
							<p>Ripple</p>
							<ul class="currency_list">
								<li><span>USD</span><p>1.322</p></li>
								<li><span>EUR</span><p>1,065</p></li>
								<li><span>GBP</span><p>0,936</p></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="rate_list text-center">
						<div class="rate_content">
							<h3>ETH</h3>
							<p>Ethereum</p>
							<ul class="currency_list">
								<li><span>USD</span><p>1,197</p></li>
								<li><span>EUR</span><p>965,0</p></li>
								<li><span>GBP</span><p>848,3</p></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="rate_list text-center">
						<div class="rate_content">
							<h3>LTC</h3>
							<p>Litecoin</p>
							<ul class="currency_list">
								<li><span>USD</span><p>182,6</p></li>
								<li><span>EUR</span><p>147,2</p></li>
								<li><span>GBP</span><p>129,4</p></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="rate_list text-center">
						<div class="rate_content">
							<h3>BTC</h3>
							<p>Bitcoin</p>
							<ul class="currency_list">
								<li><span>USD</span><p>8195</p></li>
								<li><span>EUR</span><p>6637</p></li>
								<li><span>GBP</span><p>5884</p></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!-- END CONTAINER-->
	</section>