<style type="text/css">
  body{background:url('_source/demo/img/grid10px.png') repeat -5px -5px;}
  #page {
    width:960px;
    min-height:200px;
    background:rgba(0,0,0,0.2);
    margin-top: 40px;
  }
</style>
<div id="page">
  <div class="pagebottom">
    <footer id="footer" class="group"><h3 class="hide">footer & copyright information</h3>
     <p class="copyright group-left">&copy; <?php echo date('Y'); ?> <strong>This is a grid system</strong></p>
    <a href="#page" title="back to top" class="group-right">top</a>
    </footer>
  </div>
</div>